///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/banterhouse-sfx.aks
/// Generation time: Sun Aug 30 13:43:01 EDT 2026
///

/// Song 'bh_sfx' metadata macros
#define bh_sfx_address  0x1EA0
#define bh_sfx_size          208
#define bh_sfx_end      0x1f6f

/// Song 'bh_sfx' array declaration
extern void bh_sfx[bh_sfx_size];
