///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/banterhouse-theme.aks
/// Generation time: Sun Aug 30 13:43:00 EDT 2026
///

/// Song 'bh_theme' metadata macros
#define bh_theme_address  0x0800
#define bh_theme_size         2434
#define bh_theme_end      0x1181

/// Song 'bh_theme' array declaration
extern void bh_theme[bh_theme_size];
